# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: "AlessandroMinoccheri"

branding:
  icon: "check"
  color: "blue"

description: "Use PHPArkitect via GitHub Actions to enforce architectural rules in your PHP projects."

name: "phparkitect-arkitect"

inputs:
  args:
    description: 'Arguments to pass to PHPArkitect (e.g., check, list)'
    required: false
    default: 'check'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
